apiVersion: v1
kind: Service
metadata:
  name: envoy-admin
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: admin
  selector:
    app: envoy