apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: envoy
  ports:
    - name: envoy-http
      protocol: TCP
      port: 8080
      targetPort: 8080